export const GET_CAMPSITES = 'GET_CAMPSITES';
export const CREATE_CAMPSITE = 'CREATE_CAMPSITE';
export const DELETE_CAMPSITE = 'DELETE_CAMPSITE';
export const UPDATE_CAMPSITE = 'UPDATE_CAMPSITE';

export const GET_REMINDERS = 'GET_REMINDERS';
export const CREATE_REMINDER = 'CREATE_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
export const UPDATE_REMINDER = 'UPDATE_REMINDER';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const SET_ALERT = 'SET_ALERT';
export const RESET_ALERTS = 'RESET_ALERTS';
